export WANDB_MODE=online
export CUDA_VISIBLE_DEVICES=0
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
python finetune_ligo.py \
  --model_type bert-mlm --tokenizer_name bert-large-uncased \
  --hidden_act gelu \
  --hidden_size 512 \
  --target_hidden_size 768 \
  --num_hidden_layers 24 \
  --num_attention_heads 8 \
  --target_num_attention_heads 12 \
  --intermediate_size 2048 \
  --hidden_dropout_prob 0.1 \
  --attention_probs_dropout_prob 0.1 \
  --encoder_ln_mode post-ln \
  --lr 2e-5 \
  --train_batch_size 512 \
  --train_micro_batch_size_per_gpu 128 \
  --lr_schedule step \
  --curve linear \
  --gradient_clipping 0.0 \
  --optimizer_type adamw \
  --weight_decay 0.01 \
  --adam_beta1 0.9 \
  --adam_beta2 0.98 \
  --adam_eps 1e-6 \
  --max_steps 100 \
  --num_warmup_steps 0 \
  --warmup_proportion 0.00 \
  --dataset_path /home/wk247/data/enwiki_books_128_20_ver3/finetune_40/ \
  --output_dir /home/wk247/saved_models/ligo-bert-2steps/ \
  --job_name sqrtlarge-hf \
  --current_run_id finetune-100steps-nowarmup-bsz512-lr2e-5-eyeinit-untie-noavg-val20-base1e-4 \
  --project_name ligo-finetuning \
  --seed 33 \
  --fp16 \
  --do_stitch \
  --hf_architecture \
  --do_validation \
  --validation_micro_batch 64 \
  --validation_shards 3 \
  --num_steps_between_checkpoints 20 \
  --num_src_models 2 \
  --src_model1_path /home/wk247/saved_models/pretrain-2steps/halflarge-hf-set0-bsz512-200ksteps-5kwarmup-5val-lr1e-4-50ksave/set0-bsz512-200ksteps-5kwarmup-5val-lr1e-4-50ksave/epoch167_step50267 \
  --src_model2_path /home/wk247/saved_models/pretrain-2steps/halflarge-hf-set1-bsz512-200ksteps-5kwarmup-5val-lr1e-4-50ksave/set1-bsz512-200ksteps-5kwarmup-5val-lr1e-4-50ksave/epoch167_step50267 \
  --untie_weights True \
  --avg_decoder False \
  --init_type eye